### 添加选课
POST {{learning_host}}/learning/choosecourse/125
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIzLTAzLTI5VDIwOjI0OjU1XCIsXCJpZFwiOlwiNTNcIixcIm5hbWVcIjpcIlVzZXJcIixcIm5pY2tuYW1lXCI6XCLlpKfonJzonIJcIixcInBhc3N3b3JkXCI6XCIqXCIsXCJwZXJtaXNzaW9uc1wiOltdLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJ0ZXN0XCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MDUzNTMxNSwiYXV0aG9yaXRpZXMiOlsieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9iYXNlIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9kZWwiLCJ4Y190ZWFjaG1hbmFnZXJfY291cnNlX2xpc3QiLCJ4Y190ZWFjaG1hbmFnZXJfY291cnNlX3BsYW4iLCJ4Y190ZWFjaG1hbmFnZXJfY291cnNlIiwiY291cnNlX2ZpbmRfbGlzdCIsInhjX3RlYWNobWFuYWdlciIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfbWFya2V0IiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9wdWJsaXNoIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9hZGQiXSwianRpIjoiZmE1OTE2ZWMtMTg1Mi00NjE0LWFhNWQtM2Q3NGU3YzBkMTBkIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.odVVk8HJJIFbojhqQt27O-BrHfu97k_0p5xXRsid93o